import "../globals.css";
import MobileNavbar from "../_components/MobileNavbar";
import Navbar from "../_components/Navbar";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function ProductsLayout({ children }) {
    return (
        <>
            <Navbar />
            <MobileNavbar />
            <main>{children}</main>
        </>

    );
}
