import "../globals.css";
import MobileNavbar from "../_components/MobileNavbar";
import Navbar from "../_components/Navbar";
import { getCategories } from "../_services/api";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function ProductsLayout({ children }) {
    const categories = await getCategories()
    console.log(categories)
    return (
        <>
            <Navbar categories={categories} />
            <MobileNavbar categories={categories} />
            <main>{children}</main>
        </>

    );
}
