import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./_components/ThemeProvider";
import HomeNavbar from "./_components/HomeNavbar";
import { I18nProvider } from "./i18n-provider"; // <-- 1. IMPORT THE PROVIDER

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // The lang="en" is removed, as our provider now handles it dynamically
    <html suppressHydrationWarning>
      <body
        className={` ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 2. WRAP YOUR COMPONENTS WITH THE PROVIDER */}
        <I18nProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* <HomeNavbar /> */}
            <main>
              {children}
            </main>
          </ThemeProvider>
        </I18nProvider>
      </body>
    </html>
  );
}